### PR TITLE
Inlay Hints: better support for destructuring

### LINKED ISSUE #536: Inlay hint incorrectly shows type of first binding of destructured record for entire record
Pre-release version `1.5.11`.

```res
type foo = {
  a: int,
  b: bool,
}

let bar = () => ({a: 0, b: true}, "123")

let ({a, b}, _) = bar()
```

inlay-hint-bug

To me, this incorrectly suggests `{a, b}` has type `int`.

### PR DESCRIPTION
**Pull request by aspeddro**
Fix #536 

image

### CODE REVIEW

File: analysis/src/Commands.ml [hunk 1]
```diff
@@ -395,7 +395,7 @@ let test ~path =
           | "dia" -> diagnosticSyntax ~path
           | "hin" ->
             let line_start = 0 in
-            let line_end = 6 in
+            let line_end = 34 in
```
Comment (cristianoc) [inline analysis/src/Commands.ml:398]: Just noticed this now -- would you add a comment about the line number hardcoded in the test?

**Review by cristianoc — APPROVED** [review]
Thanks for improving this.
Would you rebase on master to address merge conflicts. Then we can merge.

File: analysis/src/Commands.ml (hunk 1 above)
Comment (aspeddro) [reply analysis/src/Commands.ml:401]: Done
