### PR TITLE
fix: Incorrect type hint for module type

### LINKED ISSUE #571: Incorrect type hint for module type
```rescript
module type A = {
  let f: unit => unit
}
```

When hovering on `A`, a type hint is shown with

```rescript
module A = {
  let f: unit => unit
}
```

(with `module` instead of `module type`).

### PR DESCRIPTION
**Pull request by aspeddro**
Close #571

### CODE REVIEW

File: analysis/src/SharedTypes.ml [hunk 1]
```diff
@@ -6,7 +6,7 @@ type modulePath =
   | File of Uri.t * string
   | NotVisible
   | IncludedModule of Path.t * modulePath
-  | ExportedModule of string * modulePath
+  | ExportedModule of string * modulePath * bool
```
Comment (cristianoc) [inline analysis/src/SharedTypes.ml:9]: This is getting a bit confusing above, what about an inline record so the 3 components of the payload are named.

**Review by cristianoc — APPROVED** [review]
Thanks for fixing this!
A style suggestion.

File: analysis/src/SharedTypes.ml (hunk 1 above)
Comment (aspeddro) [reply analysis/src/SharedTypes.ml]: Done
